### ISSUE TITLE
TypeError: hostName.join is not a function error running 

### ISSUE THREAD

**Issue by gyorgycsefan** [martijnvandervlag/newman-reporter-junitfull#4]
When running the below command: 

newman run ipfile.postman_collection.json -e jo.ipas\ \(docker\ dev\).postman_environment.json -r junitfull --reporter-junitfull-export newman/junitfull.xml

I get this response:

/usr/local/lib/nodejs/node-v16.15.0-linux-x64/lib/node_modules/newman-reporter-junitfull/lib/index.js:69
			testsuite.att('hostname', protocol + hostName.join('.'));
			                                              ^

TypeError: hostName.join is not a function
    at /usr/local/lib/nodejs/node-v16.15.0-linux-x64/lib/node_modules/newman-reporter-junitfull/lib/index.js:69:50
    at arrayEach (/usr/local/lib/nodejs/node-v16.15.0-linux-x64/lib/node_modules/newman-reporter-junitfull/node_modules/lodash/lodash.js:530:11)
    at Function.forEach (/usr/local/lib/nodejs/node-v16.15.0-linux-x64/lib/node_modules/newman-reporter-junitfull/node_modules/lodash/lodash.js:9410:14)
    at EventEmitter.<anonymous> (/usr/local/lib/nodejs/node-v16.15.0-linux-x64/lib/node_modules/newman-reporter-junitfull/lib/index.js:58:5)
    at EventEmitter.emit (/usr/local/lib/nodejs/node-v16.15.0-linux-x64/lib/node_modules/newman/node_modules/eventemitter3/index.js:203:33)
    at done (/usr/local/lib/nodejs/node-v16.15.0-linux-x64/lib/node_modules/newman/lib/run/index.js:314:29)
    at /usr/local/lib/nodejs/node-v16.15.0-linux-x64/lib/node_modules/newman/node_modules/postman-runtime/lib/backpack/index.js:58:34
    at PostmanCollectionRun._process (/usr/local/lib/nodejs/node-v16.15.0-linux-x64/lib/node_modules/newman/node_modules/postman-runtime/lib/runner/run.js:160:13)
    at PostmanCollectionRun.<anonymous> (/usr/local/lib/nodejs/node-v16.15.0-linux-x64/lib/node_modules/newman/node_modules/postman-runtime/lib/runner/run.js:166:76)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

I run on Amazon Linux with:
newman 5.3.2
Node v16.15.0
reporter-junitfull 1.1.1

**Comment by masuggs515** [comment]
I am running in to this same issue @gyorgycsefan  did you find a resolution to this?

**Comment by gyorgycsefan** [comment]
@masuggs515 : I have not found a solution for this within the available time. It looked to me as if it requires a URL like the postman API URL to be passed in. I switched to junit reporter which worked like charm in my case.

I used the command like this:
newman run ./collection.json -e environment.json -r junit --reporter-junit-export newman/junitreport.xml
